### ISSUE TITLE
DCloud云函数管理应该如何配置

### ISSUE THREAD

**Issue by zwdgit** [zwpro/coupons#13]
![image](https://user-images.githubusercontent.com/28926324/100828757-cd5d8c00-349a-11eb-8743-7acb7af7d4c2.png)

我是这样配置的，但是一直报404

**Comment by zwdgit** [comment]
现在可以访问到了，但是返回的数据一直为 null，云数据库是有数据的
![image](https://user-images.githubusercontent.com/28926324/100830987-c8e7a200-349f-11eb-82ad-451a98f7f309.png)
![image](https://user-images.githubusercontent.com/28926324/100831053-e157bc80-349f-11eb-997f-da68660d58b1.png)

**Comment by zwpro** [comment]
> 现在可以访问到了，但是返回的数据一直为 null，云数据库是有数据的
> ![image](https://user-images.githubusercontent.com/28926324/100830987-c8e7a200-349f-11eb-82ad-451a98f7f309.png)
> ![image](https://user-images.githubusercontent.com/28926324/100831053-e157bc80-349f-11eb-997f-da68660d58b1.png)

设置云函数访问path为 /http/api

**Comment by zwpro** [comment]
云开发部署教程：http://lianghua.wxthe.com/docs/
