### ISSUE TITLE
淘宝联盟中饿了么订单支付消息如何获取 

### ISSUE THREAD

**Issue by zzk1314** [zwpro/coupons#52]
美团联盟已调试成功，可以拿到用户扫码下单的消息推送。

但是淘宝联盟中的-饿了么订单该怎么拿啊，我注册淘宝联盟找了一晚上都没找到。。

求教！

**Comment by chofan007** [comment]
你好，能请教一下美团扫描下单这个怎么操作的呀

**Comment by zwpro** [comment]
> 美团联盟已调试成功，可以拿到用户扫码下单的消息推送。
> 
> 但是淘宝联盟中的-饿了么订单该怎么拿啊，我注册淘宝联盟找了一晚上都没找到。。
> 
> 求教！

淘宝客-推广者-所有订单查询：https://open.taobao.com/api.htm?spm=a219a.7386797.0.0.54e9669a6NLHFa&source=search&docId=43328&docType=2

**Comment by zzk1314** [comment]
> > 美团联盟已调试成功，可以拿到用户扫码下单的消息推送。
> > 但是淘宝联盟中的-饿了么订单该怎么拿啊，我注册淘宝联盟找了一晚上都没找到。。
> > 求教！
> 
> 淘宝客-推广者-所有订单查询：https://open.taobao.com/api.htm?spm=a219a.7386797.0.0.54e9669a6NLHFa&source=search&docId=43328&docType=2

感谢回复! 
这个接口是需要定向授权得吧，我申请的淘宝账号没有找到这个权限，请问你这边是怎么获取接口权限的啊。

**Comment by zwpro** [comment]
> > > 美团联盟已调试成功，可以拿到用户扫码下单的消息推送。
> > > 但是淘宝联盟中的-饿了么订单该怎么拿啊，我注册淘宝联盟找了一晚上都没找到。。
> > > 求教！
> > 
> > 
> > 淘宝客-推广者-所有订单查询：https://open.taobao.com/api.htm?spm=a219a.7386797.0.0.54e9669a6NLHFa&source=search&docId=43328&docType=2
> 
> 感谢回复!
> 这个接口是需要定向授权得吧，我申请的淘宝账号没有找到这个权限，请问你这边是怎么获取接口权限的啊。

申请appkey，可以有权限

**Comment by zzk1314** [comment]
> > > > 美团联盟已调试成功，可以拿到用户扫码下单的消息推送。
> > > > 但是淘宝联盟中的-饿了么订单该怎么拿啊，我注册淘宝联盟找了一晚上都没找到。。
> > > > 求教！
> > > 
> > > 
> > > 淘宝客-推广者-所有订单查询：https://open.taobao.com/api.htm?spm=a219a.7386797.0.0.54e9669a6NLHFa&source=search&docId=43328&docType=2
> > 
> > 
> > 感谢回复!
> > 这个接口是需要定向授权得吧，我申请的淘宝账号没有找到这个权限，请问你这边是怎么获取接口权限的啊。
> 
> 申请appkey，可以有权限

我申请的appKey里没有这个权限 😿
ps. 方便加微信沟通么，想跟你咨询一下！ 
我的微信号  NeThunder

**Comment by zwpro** [comment]
> NeThunder

加 sanxungo 备注github，拉你进群

**Comment by FatDong1** [comment]
@zzk1314 老哥权限申请成功了吗

**Comment by zpzxgcr** [comment]
@zzk1314 兄弟我请客和你一样的最后怎么解决的
